language: php

php:
    - 5.6

services:
    - mysql

before_script:
  - composer self-update
  - mysql -u root -e 'create database testdbtautof;'
  - composer install

script: phpunit --coverage-text

notifications:
  email:
    -  lionel.duboeuf@gmail.com
